name: base_clean_architecture
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependency_overrides:
  analyzer: 6.3.0

dependencies:
  android_id: ^0.3.3
  async: ^2.11.0
  auto_route: ^7.8.4
  clock: ^1.1.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartx: ^1.2.0
  device_info_plus: ^9.0.2
  dio: ^5.4.0
  encrypted_shared_preferences: ^3.0.1

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_cache_manager: ^3.3.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_udid: ^2.0.1
  get_it: ^7.6.7
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.4
  intl: ^0.19.0
  # objectbox: ^2.5.0
  # objectbox_flutter_libs: ^2.5.0
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  provider: ^6.1.1
  retrofit: ^4.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: 6.0.17
  url_strategy: ^0.2.0
  visibility_detector: ^0.4.0+2
  

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: 2.4.5
  flutter_gen_runner: 5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  # objectbox_generator: ^2.5.0

# objectbox:
#   output_dir: src/repository/source/database/generated

# Config generate when build
flutter_gen:
  output: lib/presentation/resource/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
